version: '3.4'
services:
  db:
    image: postgres:13
    restart: always
    hostname: db
    environment:
      POSTGRES_PASSWORD: Pass2word
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - agr
    ports:
      - "5432:5432"
  admin:
    image: dpage/pgadmin4
    hostname: admin
    environment:
      PGADMIN_DISABLE_POSTFIX: "true"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_DEFAULT_EMAIL: "test@test.test"
    ports:
      - "8080:80"
    networks:
      - agr
    volumes:
      - ./share:/var/lib/pgadmin
volumes:
  postgres:
  pgadmin:
networks:
  agr:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
