import {Column, Entity, PrimaryGeneratedColumn} from "typeorm";

@Entity('medical')
export class MedicalEntity{
  @PrimaryGeneratedColumn()
  id:number;
  @Column({name:'first_name'})
  firstName:string;
  @Column({name:'last_name'})
  lastName:string;
  @Column({name:'birth_date'})
  birthDate:string;
  @Column({name:'national_id'})
  nationalID:string;
  @Column({name:'measurement_date'})
  measurementDate:string;
  @Column()
  country:string;
  @Column()
  state:string;
  @Column()
  city:string;
  @Column()
  address:string;
  @Column({name:'temperature_09_00'})
  temperature0900:number;
  @Column({name:'temperature_14_00'})
  temperature1400:number;
  @Column({name:'temperature_18_00'})
  temperature1800:number;
  @Column({name:'temperature_21_00'})
  temperature2100:number;
  @Column({name:'press_sys_09_00'})
  bloodPressureSystolic0900:number;
  @Column({name:'press_dia_09_00'})
  bloodPressureDiastolic0900:number;
  @Column({name:'press_sys_14_00'})
  bloodPressureSystolic1400:number;
  @Column({name:'press_dia_14_00'})
  bloodPressureDiastolic1400:number;
  @Column({name:'press_sys_18_00'})
  bloodPressureSystolic1800:number;
  @Column({name:'press_dia_18_00'})
  bloodPressureDiastolic1800:number;
  @Column({name:'press_sys_21_00'})
  bloodPressureSystolic2100:number;
  @Column({name:'press_dia_21_00'})
  bloodPressureDiastolic2100:number;
  @Column({name:'pulse_09_00'})
  pulse0900:number;
  @Column({name:'pulse_14_00'})
  pulse1400:number;
  @Column({name:'pulse_18_00'})
  pulse1800:number;
  @Column({name:'pulse_21_00'})
  pulse2100:number;
  @Column({name:'blood_heamoglobin'})
  hemoglobin:number;
  @Column({name:'blood_wbc'})
  wbc:number;
  @Column({name:'blood_mcv'})
  mcv:number;
  @Column({name:'blood_pcv'})
  pcv:number;
  @Column({name:'blood_rbc'})
  rbc:number;
  @Column({name:'blood_mch'})
  mch:number;
  @Column({name:'blood_mchc'})
  mchc:number;
  @Column({name:'blood_rdw'})
  rdw:number;
  @Column({name:'blood_neutrophils'})
  neutrophils:number;
  @Column({name:'blood_lymphocytes'})
  lymphocytes:number;
  @Column({name:'blood_monocytes'})
  monocytes:number;
  @Column({name:'blood_eosinophils'})
  eosinophils:number;
  @Column({name:'blood_basophils'})
  basophils:number;

}
