export interface MedicalRecord{
  id?:string;
  index_number?:number;
  firstName?:string;
  lastName?:string
  tempIn9?:number,
  tempIn14?:number,
  birthDate?:string|Date;
  nationalId?:string;
  measurementDate?:string|Date;
  country?:string;
  state?:string;
  city?:string;
  address?:string;
  temperature0900?:number;
  temperature1400?:number;
  temperature1800?:number;
  temperature2100?:number;
  bloodPressureSystolic0900?:number;
  bloodPressureDiastolic0900?:number;
  bloodPressureSystolic1400?:number;
  bloodPressureDiastolic1400?:number;
  bloodPressureSystolic1800?:number;
  bloodPressureDiastolic1800?:number;
  bloodPressureSystolic2100?:number;
  bloodPressureDiastolic2100?:number;
  pulse0900?:number;
  pulse1400?:number;
  pulse1800?:number;
  pulse2100?:number;
  hemoglobin?:number;
  wbc?:number;
  mcv?:number;
  pcv?:number;
  rbc?:number;
  mch?:number;
  mchc?:number;
  rdw?:number;
  neutrophils?:number;
  lymphocytes?:number;
  monocytes?:number;
  eosinophils?:number;
  basophils?:number;
}
